# This is a basic workflow to help you get started with Actions

name: Vault and GitHub demo
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Get-a-Secret:
    runs-on: self-hosted
    steps:
      
      - name: Import environment variables
        run: |
          echo ROLE_ID="$ROLE_ID" >> $GITHUB_ENV
          echo SECRET_ID="$SECRET_ID" >> $GITHUB_ENV

      - name: Retrieve the secret
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: https://vaultazure.philips-hdstest.com
          method: approle
          roleId: ${{ env.ROLE_ID }}
          secretId: ${{ env.SECRET_ID }}
          tlsSkipVerify: true
          secrets: |
            /dicom-gateway/data/client-test/us-east/oauth2 client-id | THE_SECRET ;

      - name: Prove it
        run: |
          echo $THE_SECRET | cut -d . -f 1
          echo $THE_SECRET | cut -d . -f 2
